sudo: false
language: node_js
node_js:
  - "16"
  - "14"
  - "12"
before_script: 
 - npm install -g istanbul
script: istanbul cover -v test/run.js 
after_success:
 - npm install -g codeclimate-test-reporter
 - codeclimate-test-reporter < coverage/lcov.info
env: 
 - CODECLIMATE_REPO_TOKEN=2ec835187f41b7f818cfa674baaf0048908beabca4d576692844b1d6739e3258  
